### ISSUE TITLE
Generate README in helm chart

### ISSUE THREAD

**Issue by sagikazarmark** [bank-vaults/vault-secrets-webhook#18]
Generate the readme using [helm-docs](https://github.com/norwoodj/helm-docs) for the helm chart.

Examples:

- https://github.com/bank-vaults/vault-operator/tree/main/charts/vault-operator
- https://github.com/sagikazarmark/helm-charts

**Comment by ramizpolic** [comment]
https://github.com/bank-vaults/vault-operator/tree/main/deploy/charts/vault-operator
