### ISSUE TITLE
Setting the seccompProfile in the SecurityContext for containers

### ISSUE THREAD

**Issue by jon-rei** [bank-vaults/vault-secrets-webhook#199]
It would be great if the seccompProfile in the SecurityContext could be configured for the containers, or set by default. The configuration would probably need to be done here: https://github.com/bank-vaults/vault-secrets-webhook/blob/main/pkg/webhook/pod.go#L858

This is particularly useful for the init containers, where the seccompProfile is set on the main container rather than the pod, and where the seccompProfile configuration is enforced.

**Comment by sedadas** [comment]
@jon-rei I created a PR for this a month ago, but have not gotten any feedback since:

https://github.com/bank-vaults/vault-secrets-webhook/pull/218
