### ISSUE TITLE
Make volumeMount path agent-secrets configurable with an environment variable/ annotation

### ISSUE THREAD

**Issue by sando38** [bank-vaults/vault-secrets-webhook#236]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

When using templates with the vault-agent as in the example in your [documentation](https://bank-vaults.dev/docs/mutating-webhook/vault-agent-templating/#use-vault-ttls):

```hcl
    template {
      contents = <<EOH
        {{- with secret "database/creds/readonly" }}
        username: {{ .Data.username }}
        password: {{ .Data.password }}
        {{ end }}
      EOH
      destination = "/etc/secrets/config"
      command     = "/bin/sh -c \"kill -HUP $(pidof vault-demo-app) || true\""
    }
```
I get the following error:
```
2023-10-24T01:14:00.384Z [ERROR] agent.template.server: template server error: error="error rendering \"(dynamic)\" => \"/etc/secrets/settings.json\": failed writing file: mkdir /etc/secrets: permission denied"
```

If I use the path `/vault/secrets` it works out of the box. From the generated manifests I can see, that a volume like this is generated

```yaml
    volumeMounts:
      - name: agent-secrets
        mountPath: /vault/secrets
  volumes:
    - name: agent-secrets
      emptyDir:
        medium: Memory
```

### Proposed Solution

Would it be possible to make the path for the volumeMount `agent-secrets` configurable with an environment variable/ annotation?

### Additional Information

Vault-operator 1.21.2

Originally reported here https://github.com/bank-vaults/vault-operator/issues/239#issuecomment-1781298780

**Comment by akijakya** [comment]
> Thanks, I noticed that variable as well, however, thought it would only apply to the consul template.

There is also a `vault.security.banzaicloud.io/vault-configfile-path` annotation that configures the same variable in the code which would have been more obvious but is missing from the docs, I noted that it should be updated!
