### ISSUE TITLE
[vault-secrets-webhook] [vault-env] provide option to set more secure securityContext in `copy-vault-env` init container

### ISSUE THREAD

**Issue by sedflix** [bank-vaults/vault-secrets-webhook#244]
**Is your feature request related to a problem? Please describe.**
After upgrading vault vault-secrets-webhook to 1.15.2/1.15.3, the init containers added to pod have the following capabilities added to them CHOWN, SETFCAP, SETGID, SETPCAP, SETUID (as a part of the PR https://github.com/banzaicloud/bank-vaults/issues/1531). The permission to allow to add these capabilities in the pod should be allowed via PSP.  
This means we need to allow all the pods to use vault secrets to add the above capabilities. This goes against restricted permission for pods ([restricted-psp](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/policy/restricted-psp.yaml), [restricted PSS](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted))

**Describe the solution you'd like**
I think this feature was added to make Vault Agent Templating work. Therefore, unless and until we are using Vault Agent Templating, which we can figure out via looking the pod annotations, we shouldn't need add these extra capabilities to the init container.

Related to https://github.com/banzaicloud/bank-vaults/issues/1593

**Comment by ramizpolic** [comment]
Seems like a duplicate of https://github.com/bank-vaults/vault-secrets-webhook/issues/199.
