### ISSUE TITLE
vault-secrets-webhook in air-gapped environment

### ISSUE THREAD

**Issue by johnny990** [bank-vaults/vault-secrets-webhook#252]
Hi,
I'm trying to deploy vault-secrets-webhook to air-gapped environment and some strange things happened. I have both unsealing vault (which stores it's unseal token in k8s secret) and application vault on the same cluster which stores unseal token in unsealing vault (not sure that this matters but for the sake of completeness I leave this info here).
When I deployed this scheme for the first time (initial deployment) everything was good - I successfully connected to the application vault, added secrets and pod injection was working.
But after some time application vault stopped working and I noticed that webhook complaints:
`level=ERROR msg="Admission review error: could not mutate object: cannot fetch image descriptor: Get \"https://index.docker.io/v2/\": dial tcp: loo
kup index.docker.io on 10.43.0.10:53: server misbehaving" app=vault-secrets-webhook svc=http.Handler kind=v1/Pod path=/pods webhook-id=vault-secrets-pods wh-version=v1beta1 dry-run=false op=create webhook-kind=mutating request-id
=6273782c-7215-424c-aaaf-aecd45df3513 name=vault-0 ns=vault-prod trace-id=""`

I've noticed that in previous deployment I was using `latest` tag for vault image, so it explains why webhook tries to get metadata from docker hub. But then I've change tag to `1.15.1`, restarted everything, wiped images from k3s, added them again, etc. And that didn't help. Webhook doesn't inject secrets and I can't start my application vault.

Is it possible somehow to completely disable connections to docker registry? Is it possible to fix the current deployment by enforcing webhook to look into the image metadata?

**Comment by johnny990** [comment]
actually, the case is more simple, I just installed single instance of vault (without this chaining mentioned above) and my workloads not starting because mutating webhook tries to connect to docker registry no matter which images I use for workloads (pulllpolicy: never, explicit version, different registries in metadata). And workload itself gets started, so image is present inside kubernetes, just not mutated.

**Comment by macrokernel** [comment]
Not stale
