### ISSUE TITLE
Single source of truth for annotation names

### ISSUE THREAD

**Issue by akijakya** [bank-vaults/vault-secrets-webhook#253]
If the annotations used to configure the webhook and vault-env would be exported consts, their values would only be set once and those could be used in `vault-env`, `secret-init` and `vault-secrets-reloader` as the single source of truth, making it easier to change them if the need arises without breaking the whole ecosystem.

**Comment by ramizpolic** [comment]
+1 for this, but not sure how big of a priority this is. would be good to handle annotations better
