### ISSUE TITLE
cannot fetch image descriptor: Get "https://index.docker.io/v2/

### ISSUE THREAD

**Issue by sdevang** [bank-vaults/vault-secrets-webhook#291]
Hi there,

We have deployed bank-vaults into a secure environment where there is no external connectivity to dockerhub. We see following error when the admission controller is trying to mutate the pod spec.

`vault-secrets-webhook-7857b544ff-r8bvp vault-secrets-webhook time="2022-10-03T10:30:21Z" level=error msg="Admission review request failed" app=vault-secrets-webhook dry-run=false error="cannot fetch image descriptor: Get \"https://index.docker.io/v2/\": dial tcp 3.228.146.75:443: i/o timeout" kind=v1/Pod name= ns=default op=create path=/pods request-id=a64e229b-956-4fed-8f06-e2ef9aed82 webhook-id=vault-secrets-pods webhook-kind=mutating wh-version=v1beta1`

How do we configure bank vaults to completely bypass going to the docker hub.

Regards,
Dev

**Comment by akijakya** [comment]
Anyone finding this issue: there is a section about using private registries in the [docs](https://bank-vaults.dev/docs/mutating-webhook/configuration/#registry-access).
