### ISSUE TITLE
Option to remove vault-env binary after startup

### ISSUE THREAD

**Issue by ronballesteros** [bank-vaults/vault-secrets-webhook#404]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-secrets-webhook/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

We use vault secret webhooks in our k8s cluster and its great that we're able to invoke secrets using env_vars without having to define secret resources.  The challenge that we're facing is that users with exec access to the pod itself can execute the vault-env binary and replay the secrets.  Has anyone thought about removing access to the  vault-env binary and if so, would love to hear how you resolved it.  Would be nice to have some kind of implementation where we can invoke an annotation where access to vault-env binary is restricted.  Thoughts?

### Proposed Solution

Unsure at this time but maybe some kind of annotation to prevent from replaying the secrets?

**Comment by csatib02** [comment]
Closing this, as it has already been discussed on Slack.

**Comment by eduardmak** [comment]
What's the reason for closing? UP

**Comment by csatib02** [comment]
@eduardmak

The reason for closing is the discussion we had on Slack: <https://outshift.slack.com/archives/CFJJW9L94/p1713810452373179>

Without going into details again, it is not a feasible idea and won't solve the actual problem.

Please read the comments next time. :)
