### ISSUE TITLE
Annotation `vault-agent-env-variables` does not work

### ISSUE THREAD

**Issue by 4FunAndProfit** [bank-vaults/vault-secrets-webhook#491]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-secrets-webhook/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Vault Secrets Webhook Version

1.21.2

### Installation Type

Official Helm chart

### Kubernetes Version

1.29

### Kubernetes Distribution/Provisioner

GKE

### Expected Behavior

Hello,

As referenced in https://github.com/bank-vaults/vault-secrets-webhook/blob/main/pkg/common/common.go#L84, there is an annotation identified with "vault.security.banzaicloud.io/vault-agent-env-variables".

I tried to use it with : 
```
      "vault.security.banzaicloud.io/vault-agent-configmap" : ...
"vault.security.banzaicloud.io/vault-agent-env-variables" : "SKIP_SETCAP=true"
``` 

But the env variable is not added in the container of Vault-Agent

Have you an idea ? Maybe it is me who do it wrong

Thanks a lot in advance,

FP

### Actual Behavior

Env var is not set

**Comment by csatib02** [comment]
Hey @4FunAndProfit,
Thanks for using Bank-Vaults!

This annotation is used to pass env-vars to the [Vault agent](https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent) sidecar, and not to Vault Env.
```go
vault.security.banzaicloud.io/vault-agent-env-variables
```

If you would like to pass env-vars to Vault Env, use:
```go
vault.security.banzaicloud.io/vault-env-passthrough
```

**Comment by 4FunAndProfit** [comment]
@csatib02, Sorry there is a mistake on my description issue (was tired when i wrote it i think)

I said vault env but it is on my Vault Agent container which does not have the env, not vault env 

So i think it is a bug ?

**Comment by 4FunAndProfit** [comment]
For information, maybe related, i use: 
"vault.security.banzaicloud.io/vault-agent-configmap"
but not "vault.security.banzaicloud.io/vault-agent"

**Comment by csatib02** [comment]
I would suggest going through our documentation on using Vault Agent with the Webhook: <https://bank-vaults.dev/docs/mutating-webhook/vault-agent-templating/>
If you don't find anything useful I suggest you go through some of our examples, you can find it here: <https://github.com/bank-vaults/secrets-webhook/blob/main/examples/test-deploy-templating.yaml>

NOTE: The previous examples are used on our new project called the Secrets-Webhook, it uses different annotations, but it's easy to figure out which annotations to use on the old Webhook.

**Comment by 4FunAndProfit** [comment]
@csatib02 Thanks for your answer,

I have read these documents and I thank you for sending them to me,

Nevertheless, for me there is always unexpected behavior! 

Have a look: 

This works : 

```
     => "vault.security.banzaicloud.io/vault-agent" =  "true" <= added
      "vault.security.banzaicloud.io/vault-agent-configmap" : "my-configmap" 
      "vault.security.banzaicloud.io/run-as-group"= "636"
      "vault.security.banzaicloud.io/run-as-user"= "100"
      "vault.security.banzaicloud.io/vault-agent-env-variables" = "SKIP_SETCAP=true"
```


This don't work : 
```
      "vault.security.banzaicloud.io/vault-agent-configmap" : "my-configmap" 
      "vault.security.banzaicloud.io/run-as-group"= "636"
      "vault.security.banzaicloud.io/run-as-user"= "100"
      "vault.security.banzaicloud.io/vault-agent-env-variables" = "SKIP_SETCAP=true"
```

Error on Vault agent container: 
`unable to set CAP_SETFCAP effective capability: Operation not permitted`
=> env is not given here (same for skip chown)

**Comment by csatib02** [comment]
I've check the code, and you always need to set `vault.security.banzaicloud.io/vault-agent: "true"`, otherwise the Vault Agent won't be used, and the `vault.security.banzaicloud.io/vault-agent-env-variables` annotation will be completely ignored.

Referring to the docs:
```
When to use vault-agent

You have an application or tool that requires to read its configuration from a file.
You wish to have secrets that have a TTL and expire.
You have no issues with running your application with a sidecar.
```

Moreover, checking the [code](https://github.com/bank-vaults/vault-secrets-webhook/blob/4dd803e62959ffddbf0d4f978beb60f36123aec1/pkg/webhook/pod.go#L837-L844) I saw that env-vars are expected to be in JSON format, I would give that a go too.

**Comment by 4FunAndProfit** [comment]
Okay thanks for all these information @csatib02 
Have a good day :)
