### ISSUE TITLE
Secrets webhook breaks default SCC

### ISSUE THREAD

**Issue by akijakya** [bank-vaults/vault-secrets-webhook#57]
Bringing this old issue here, as it seems to be one of the greatest pain points for BV users that still generates activity today:

https://github.com/banzaicloud/bank-vaults/issues/1593

**Comment by sagikazarmark** [comment]
TODO: transfer the issue itself to this project once BV repo is migrated to the org.

**Comment by sagikazarmark** [comment]
See #69
