### ISSUE TITLE
[vault-secrets-webhook] GRPC Liveness and Readiness Probes Getting Removed During Mutation

### ISSUE THREAD

**Issue by anthonytabone** [bank-vaults/vault-secrets-webhook#80]
**Describe the bug**:
If a pod uses GRPC Readiness and Liveness probes, after the pod is mutated, they are removed from the pod's spec preventing the pods from being able to get scheduled as the scheduler reports: 
`Error creating: Pod "xxxxxxxxx" is invalid: [spec.containers[0].livenessProbe: Required value: must specify a handler type, spec.containers[0].readinessProbe: Required value: must specify a handler type]`

**Expected behaviour**:
The GRPC Liveness and Readiness probes shouldn't be removed when the pod's spec is mutated.

**Steps to reproduce the bug**:
Add necessary annotations to a deployment that uses GRPC Liveness and Readiness probes.

**Additional context**:
Debug logs from the vault-secrets-webhook pods confirm that the probes are getting removed:
`{\"op\":\"remove\",\"path\":\"/spec/containers/0/livenessProbe/grpc\"},{\"op\":\"remove\",\"path\":\"/spec/containers/0/readinessProbe/grpc\"}`

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.26.3
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AWS using Kops
- bank-vaults version (e.g. 0.4.17): 1.19.0
- Install method (e.g. helm or static manifests): Static manifests generated from Helm chart
- Logs from the misbehaving component (and any other relevant logs): `{\"op\":\"remove\",\"path\":\"/spec/containers/0/livenessProbe/grpc\"},{\"op\":\"remove\",\"path\":\"/spec/containers/0/readinessProbe/grpc\"}`
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: N/A

/kind bug

**Comment by akijakya** [comment]
In the latest (1.20.0) webhook version the k8s api version got upgraded above 0.27 so I assume this is now resolved, @anthonytabone feel free to reopen if you still experience issues about it!
