### ISSUE TITLE
New annotation handling at mutating webhooks

### ISSUE THREAD

**Issue by lagunary** [bank-vaults/vault-secrets-webhook#86]
This request is not related for a reported problem, but it could be happened accidentally.

New feature: 
At the mutating webhook type of vault-operator would be so nice if it can handle a new annotation about the version of a complete list.
e.g.: 
these are some of available annotations:
 - vault.security.banzaicloud.io/vault-addr: https://vault.somedomain.smg
 - vault.security.banzaicloud.io/vault-env-from-path: kv-v2/data/somelist
 - vault.security.banzaicloud.io/vault-path: somepath
 - vault.security.banzaicloud.io/vault-role: somerole
this one would be so useful:
  - vault.security.banzaicloud.io/vault-list-version: somevalue (e.g.: 5)
  [default value: highest version, this annotation is optional]

This feature could avoid of the accidentally changed value of any key of list.
Use case:
Multiple membered team is working on a certificate keypair change for client auth of an application which is running on a k8s cluster.
If one of them has been replaced the new private key as vault list element. From this point the pod of the application can be restarted (not manually, just cause of usage peak, cluster will react for usage with horizontalScaling) with the new private key cause of the mutating webhook mode of vault agent works with init-container, and the init-container downloads and inject value into the running pod.
This problem wont be seen if the vault operator can handle versions of a list in vault.

If you also see potential on this feature, don't hesitate to contact me for more details.
Thanks in advance.
Viktor

**Comment by ramizpolic** [comment]
Hi @lagunary, thanks for taking the time to submit the proposal. I am not entierly sure what you mean by _avoid of the accidentally changed value of any key of list_. Would you be able to explain it using an example in mind? Thanks a lot!

**Comment by lagunary** [comment]
The main target that you can handle secret list versions in a runtime (application). Example scenario: You know that the apllication’s database user’s password will be changed at 22.00. You also know that you will make another version from this list with the new sql user password. But you cant do it before the password changes (in thise at 22.00). Cause the webhook will inject ALWAYS the latest version from that list. Imagine that you replace password before 22.00. (Details: app1 uses latest version list : version40, you made version41). If the applicaton (app1) somehow restart before 22.00 the webhook will inject version41, although you would be able to set the exact version of list (version40, cause in this case this is the proper list).

I have a lot of other type examle also. If you wanna I can share more scenarios where this function can be so usefull.

Thank you.

**Comment by ramizpolic** [comment]
Thanks @lagunary! If I understood correctly, the maximum version of a specific secret that needs to be injected would be limited by this annotation. This would then ensure that we don't inject the latest version, but anything that is not over the one specified via annotation. Please feel free to include more examples regarding the use case and how it could be supported by our API.

**Comment by akijakya** [comment]
Hi @lagunary, there are ways to pin versions of secrets via [inline annotations](https://bank-vaults.dev/docs/mutating-webhook/configuration/#inline) and also via the `vault.security.banzaicloud.io/vault-env-from-path` [annotation](https://bank-vaults.dev/docs/mutating-webhook/configuration/#mount-all-keys) - are these offer a solution to what you proposed?

**Comment by akijakya** [comment]
Hi @lagunary, you can also find us on our [community Slack](https://bank-vaults.dev/docs/community/)! 😊

**Comment by lagunary** [comment]
Latest release (1.21.1 releason 2024.02.04) has this feature.
Docs: https://bank-vaults.dev/docs/mutating-webhook/configuration/#mount-all-keys
