### ISSUE TITLE
What is the current helm deploy repo

### ISSUE THREAD

**Issue by stephenwolfe1** [bank-vaults/vault-secrets-webhook#92]
Looking for the current helm repository or release strategy for this chart. https://bank-vaults.dev/docs/mutating-webhook/deploy/ still references https://kubernetes-charts.banzaicloud.com. This repo has stopped at 1.19.0. Is the version tag on this repository the current release strategy? If so, the current logic for the docker image v1.20.0 tag results in `latest` which does not seem ideal.

**Comment by LinAnt** [comment]
Hello, we are deploying v1.20.0 through oci://ghcr.io/bank-vaults/helm-charts :+1:

**Comment by sagikazarmark** [comment]
@stephenwolfe1 we've updated the documentation.

The new helm chart for the project: `oci://ghcr.io/bank-vaults/helm-charts/vault-secrets-webhook`
