### ISSUE TITLE
If vault-env-from-path annotation is in place, the copy-vault-env will not be injected on azure

### ISSUE THREAD

**Issue by josueCarvajal** [bank-vaults/vault-secrets-webhook#98]
# Problem description
When using the annotation **vault.security.banzaicloud.io/vault-env-from-path** the copy-vault-env init container will not be injected, causing the pod to crash since it cannot find the required env variables.

If you use the traditional way, it works
env:
- name: MY_ENV_VAR
   vale: vault:kv/path/to/secret

But if you use both, annotation + env or just annotation it won't inject the init container

⚠️This is only occurring on Azure, it is not occurring on AWS

## Versions used:
- docker.io/hashicorp/vault:1.14.0
- docker.io/hashicorp/vault-k8s:1.2
- banzaicloud/vault-secrets-webhook:1.19.1
- banzaicloud/vault-env:1.19.1
- Kubernetes version 1.24

**Comment by sagikazarmark** [comment]
Thanks for reporting @josueCarvajal ! Let us look into this.

**Comment by sagikazarmark** [comment]
@akijakya can you please take a look at this issue?

@josueCarvajal can you please try upgrading to the latest version to see if this is still a problem? Thanks!

**Comment by akijakya** [comment]
Could you please also provide an example of the values you put in the `vault.security.banzaicloud.io/vault-env-from-path` annotation? Thanks!

**Comment by josueCarvajal** [comment]
@sagikazarmark The issue started happening when we upgraded vault + banzai webhook + vault k8s to the versions mentioned, it was not happening when running in the following versions, so it could be a regression:
Old version used when it was working:

- docker.io/hashicorp/vault:1.10.3
- docker.io/hashicorp/vault-k8s:0.16.1
- banzaicloud/vault-secrets-webhook:1.15.3
- banzaicloud/vault-env:1.15.3


Unfortunately this environment is pretty limited to releases, so  I no longer have access to the azure env I had to move away from that annotation and started moving to configmaps and refer it as env since there are more than 150+ secrets for our app

**Comment by josueCarvajal** [comment]
@akijakya Like this, comma delimited! It was working on AWS but not on azure

`vault.security.banzaicloud.io/vault-env-from-path: "kv/${var.namespace}/id-secrets,kv/${var.namespace}/api-secrets,kv/${var.namespace}/account-secrets"`

**Comment by akijakya** [comment]
I tried to reproduce the issue on a vanilla AKS cluster with operator, webhook installed via Helm and haven't encountered any issues, although I might add that version `1.19.1` of the webhook and vault-env doesn't seem to be existing, so I tested with `1.19.0` and `latest`.

It seems likely that this is a cluster-level issue and not a bug in the webhook, maybe another webhook messes things up?, but it sounds really strange that it depends on an annotation, whether a request gets to the webhook or not, and the resource gets created anyway. @sagikazarmark do you have anything to add?
